# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mohamed Elhefny
description: "Hi, I’m Mohamed, an Applied AI / Data Scientist. Here you’ll find end to end projects that prioritize ROI, adoption, and measurable outcomes. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Applied AI / Data Science <span style="color:#f58506"> Portfolio </span>
location: "Melbourne, AUS"
resume_url: /docs/Mohamed Elhefny -CV.docx
avatar_image: /img/Personal Photo-02.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/mohamed-elhefny" # Add your linkedln handle
github: "https://github.com/melhefny.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




